accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

job_portal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from core import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('accounts.urls')),
    path('', include('dashboard.urls')),
    path('', include('candidate.urls')),
    path('', include('price_plan.urls')),
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class RegisterInfoModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.BooleanField(default=False)
    candidate = models.BooleanField(default=False)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import RegisterInfoModel
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(help_text='')
    email = forms.CharField(label='Email', widget=forms.EmailInput())
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput())

    company = forms.BooleanField(required=False)
    candidate = forms.BooleanField(required=False)
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('username', 'email', 'password1', 'password2', 'company', 'candidate')
    
    

accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .models import RegisterInfoModel
from price_plan.models import PricePlanModel

def register(request):
    if request.method == 'POST':
        fm = RegisterForm(request.POST)
        if fm.is_valid():
            fm.save()
            username = fm.cleaned_data.get('username')
            company = fm.cleaned_data.get('company')
            candidate = fm.cleaned_data.get('candidate')
                
            user = User.objects.get(username = username)
            user_info = RegisterInfoModel.objects.create(user = user, company = company, candidate = candidate) 
            user_info.save()
            if candidate:
                price_user = User.objects.get(username = username)
                my_user = PricePlanModel.objects.create(user = price_user, plan = 'Free')
            return redirect('login')
    else:
        fm = RegisterForm()
    return render(request, 'accounts/signup.html', {'form': fm})


def user_login(request):
    if request.method == 'POST':
        fm = AuthenticationForm(request=request, data = request.POST)
        if fm.is_valid():
            user_username = request.POST.get('username')
            user_pass = request.POST.get('password')
            user = authenticate(username = user_username, password = user_pass)

            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        fm = AuthenticationForm() 
    return render(request, 'accounts/login.html', {'form': fm})


def user_logout(request):
    logout(request)
    
    return redirect('login')

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 
{% load tailwind_filters%}

{% block title %}
  Login
{% endblock title %} 
 

{% block content %}

<div class="w-[27%] mx-auto shadow-md p-5 mt-5">
    <h3 class="text-center text-3xl font-bold">Login</h3>
  <form action="" method="post" class="space-y-2">
    {% csrf_token %} 
    {{ form|crispy }}
    <input class="text-center bg-green-500 text-white py-2 px-4 rounded-md" type="submit" value="Login" />
  </form>
</div>

<div class="text-grey-dark mt-10 text-center">
  Don't have an account?
  <a class="no-underline border-b border-blue text-blue" href="{% url 'signup' %}">
    Signup </a
  >
</div>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load crispy_forms_tags %} 
{% load tailwind_filters %}

{% block title %} Signup {% endblock title %}

{% block content %}
<div class="w-[27%] mx-auto shadow-md p-5 mt-5">
    <h3 class="text-center text-3xl font-bold">Sign Up</h3>
    <form action="" method="post" class="space-y-2" id="user-form">
        {% csrf_token %} 
        {{ form|crispy }}
        <input class="text-center bg-green-500 text-white py-2 px-4 rounded-md" type="submit" value="Signup" />
    </form>
</div>

<div class="text-grey-dark mt-10 text-center mb-5">
    Already have an account?
    <a class="no-underline border-b border-blue text-blue" href="{% url 'login' %}">
        Log in
    </a>
</div>

<script>
document.addEventListener("DOMContentLoaded", function () {
    const companyCheckbox = document.querySelector("#id_company");
    const candidateCheckbox = document.querySelector("#id_candidate");

    companyCheckbox.addEventListener("change", function () {
        if (companyCheckbox.checked) {
            candidateCheckbox.checked = false;
        }
    });

    candidateCheckbox.addEventListener("change", function () {
        if (candidateCheckbox.checked) {
            companyCheckbox.checked = false;
        }
    });
});
</script>
{% endblock content %}